### PR TITLE
fix: credential provider response secret ownership

### PR DESCRIPTION
**Pull request by dkoshkin**
**What problem does this PR solve?**:
Saw that the owner was not getting correctly set on image credential Secret.

**Which issue(s) this PR fixes**:
Fixes #

**How Has This Been Tested?**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jimmidyson** [comment]
Can we add an e2e test that includes creating this kind of secret? This should automatically check ownership

**Comment by dkoshkin** [comment]
> Can we add an e2e test that includes creating this kind of secret? This should automatically check ownership

Good idea, any hints how I can do that without adding some dummy registry into the examples?

**Review by supershal — APPROVED** [review]
Thanks for fixing this. can we create a unit test for this? it can be separate PR / GH issue/Jira.

**Comment by jimmidyson** [comment]
@dkoshkin 

> any hints how I can do that without adding some dummy registry into the examples?

Ooo good question! Maybe this is easier with a envtest based test instead of our e2es?

**Comment by dkoshkin** [comment]
Adding a unit test is turning out way more complicated than it needs to be.
Using the fakeclient it fails creating the Secret because of https://github.com/kubernetes/kubernetes/issues/115598. I thought that I can pre-create an empty Secret as a workaround but its still giving me this error:
```
Received unexpected error: failed to apply Image Registry Credentials Secret: server-side apply failed: apply patches are not supported in the fake client. Follow https://github.com/kubernetes/kubernetes/issues/115598 for the current status
```

I tried writing a Ginkgo test and using envtest but thats also failing because of strange error
```
failed to apply Image Registry Credentials Secret: server-side apply failed: the server could not find the requested resource
```

Here is the commit https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/commit/1a8a1dff8430c0e1ae8f9403121e6952144a5034

If its ok, I would like to come back to the unit tests in a separate PR. I'm trying to clean up the owner refs for all these Secrets and there are still a few other ones.

**Comment by jimmidyson** [comment]
@dkoshkin 

> If its ok, I would like to come back to the unit tests in a separate PR. I'm trying to clean up the owner refs for all these Secrets and there are still a few other ones.

Sure, let's do that!

**Review by jimmidyson — APPROVED** [review]

**Pull request merged**
