### PR TITLE
fix: autogenerated file to satisfy linter

### PR DESCRIPTION
**Pull request by dkoshkin**
**What problem does this PR solve?**:
This caused a release error https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/actions/runs/11041694582/job/30713405814

**Which issue(s) this PR fixes**:
Fixes #

**How Has This Been Tested?**:

I just ran `make dev.run-on-kind` to generate these changes.

**Special notes for your reviewer**:

### CODE REVIEW

**Review by supershal — APPROVED** [review]

**Comment by thunderboltsid** [comment]
Do we have two separate linters in place for two separate workflows? I remember encountering this where pre-commit target would actually mutate this back.

**Comment by jimmidyson** [comment]
> Do we have two separate linters in place for two separate workflows? I remember encountering this where pre-commit target would actually mutate this back.

Yeah I think that's right. I think we should exclude it from the golines call somehow as part of this PR so it doesn't get reverted.

**Comment by jimmidyson** [comment]
I know it's not great but I fixed it up in https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/922/files#diff-fe1727af26e0329c2bb94f9d274ed74fa926a0a7af1392c8db761788949a0bc3 I think so it will be ignored by golines for formatting so we shouldn't see this issue again once we merge #922.

**Comment by jimmidyson** [comment]
Actually maybe better to pull those makefile changes out to this PR.

**Comment by jimmidyson** [comment]
Realised that the change I proposed to fix this going forward is not going to work so I pushed #923 as an alternative that should fix this permanently.

**Pull request closed without merging**
