### PR TITLE
fix: add omitempty to addon strategy

### PR DESCRIPTION
**Pull request by dkoshkin**
**What problem does this PR solve?**:
Saw a failure when using the API to generate a spec and not setting the `strategy` in Go code:
```
is invalid: [spec.topology.variables.addons.cni.strategy: Unsupported value: "": supported values: "ClusterResourceSet", "HelmAddon"...
```

Adding `+kubebuilder:validation:Optional` didn't change the generated CRDs, but I think we still want them?

**Which issue(s) this PR fixes**:
Fixes #

**How Has This Been Tested?**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dlipovetsky** [comment]
> Optional fields have the following properties:
> They are a pointer type in the Go definition (e.g. AwesomeFlag *SomeFlag) or have a built-in nil value (e.g. maps and slices).
> -- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required

Given https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/blob/9039258cf489e4d9e6c6d6c46fedc0b56c9b9f4a/api/v1alpha1/addon_types.go#L101

Do we want to make this a pointer to a string?

**Review by faiq — APPROVED** [review]

**Comment by jimmidyson** [comment]
> Do we want to make uses of AddonStrategy pointers?

Yes please!

**Comment by jimmidyson** [comment]
@dkoshkin 

> Adding +kubebuilder:validation:Optional didn't change the generated CRDs

That's because the `+kubebuilder:validation:Required` annotation is on the [`AddonType` type alias](https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/blob/main/api/v1alpha1/addon_types.go#L99). I've updated that now and will push in a minute.

**Comment by jimmidyson** [comment]
Switched to pointer field, fixed up handlers and tests, and pushed.

**Review by jimmidyson — APPROVED** [review]

**Review by mhrabovcin — APPROVED** [review]

**Pull request merged**
