### PR TITLE
build: Add images list make target

### PR DESCRIPTION
**Pull request by jimmidyson**
Integrate into release build so the list of images is attaches
to each release.

### CODE REVIEW

**Review by faiq — CHANGES_REQUESTED** [review]
blocking until we discuss with the team on how we want to approach this.

**Comment by jimmidyson** [comment]
> blocking until we discuss with the team on how we want to approach this.

What do you mean `how we want to approach this`?

**Comment by faiq** [comment]
Just to clarify:

I'd like to merge tooling like this when we have the following ready

- automated values for charts/cluster-api-runtime-extensions-nutanix/templates
- use this tooling with the values from there

**Comment by dlipovetsky** [comment]
I think @faiq would like to merge #798 first

**Comment by faiq** [comment]
closing this for a go implementation in #822 for more readable code.

**Pull request closed without merging**
