### PR TITLE
fix: Upgrade dynamic-credential-provider to v0.5.3

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes falling back to origin registry if mirror does not contain
requested image.

### CODE REVIEW

**Comment by dkoshkin** [comment]
We should update this in KIB first, otherwise the air-gapped tests using CAREN will fail.

**Comment by jimmidyson** [comment]
@dkoshkin 

> We should update this in KIB first, otherwise the air-gapped tests using CAREN will fail.

We don't have air-gapped tests in CAREN and I assume the air-gapped tests you're talking about use a released version of CAREN, so let's merge this here and then when we release CAREN we can update KIB and the air-gapped tests you're talking about.

**Comment by supershal** [comment]
I think @dkoshkin is referring to existing konvoy2 airgap tests that uses KIB images. We don't have env setup for automated airgap e2e tests yet. I think this PR can be merged in parallel. 
PR for KIB. https://github.com/mesosphere/konvoy-image-builder/pull/1084

Konvoy still uses `ghcr.io/mesosphere/dynamic-credential-provider:v0.2.0`.  Do we know why we havent bumped it there yet? or it needs to bumped there as well?

**Review by supershal — APPROVED** [review]

**Comment by jimmidyson** [comment]
@supershal 

> Konvoy still uses ghcr.io/mesosphere/dynamic-credential-provider:v0.2.0. Do we know why we havent bumped it there yet? or it needs to bumped there as well?

No idea, yes it needs to be bumped there as it will include newer credential providers that support the latest kubelet credential provider APIs.

**Comment by dkoshkin** [comment]
> No idea, yes it needs to be bumped there as it will include newer credential providers that support the latest kubelet credential provider APIs.

Konvoy has not migrated the API version yet.

**Comment by dkoshkin** [comment]
Lets talk about it offline first before merging please. This coordination that we need across 3 repos is not great.

**Comment by dkoshkin** [comment]
I was thinking about this some more, we can merge this and rebuild the AMIs in KIB with the same change which will be with v1.29.4 Kubernetes version and then use the new AMIs in Konvoy e2e tests.

**Review by dkoshkin — APPROVED** [review]

**Pull request merged**
