### PR TITLE
build: Update license for Nutanix

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Review by tuxtof — APPROVED** [review]

**Comment by jimmidyson** [comment]
actionlint check is failing due to the diff being too large - fixed in https://github.com/reviewdog/reviewdog/pull/1714 but that needs to be pulled into the actionlint-action which it hasn't been yet. To get this merged I would need to disable the required check there, merge this PR, then reenable the required check.

**Review by deepakm-ntnx — APPROVED** [review]
Assuming legal has approved this text. Thanks

**Review by dkoshkin — APPROVED** [review]

**Review by deepakm-ntnx — APPROVED** [review]

**Comment by msdolbey** [comment]
Should this change?
https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/blob/jimmi/nutanix-license/charts/cluster-api-runtime-extensions-nutanix/Chart.yaml#L14

Not really license related, but more d2iq related.

**Review by msdolbey — APPROVED** [review]
👍 
Legally Speaking

**Comment by jimmidyson** [comment]
@msdolbey Not yet... Working on migrating content from there but it's Kubernetes focused so we want to move it and repoint there.

**Pull request merged**
